### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cynnek** [alionar/nikeid-telegram-scrapper#4]
Hi alionar,

I encountered the following error thereafter. I guess it is not pulling out the list? Thanks!

Traceback (most recent call last):
  File "nikeid-telegram-scrapper.py", line 167, in <module>
    main()
  File "nikeid-telegram-scrapper.py", line 155, in main
    kirim_telegram = filtering_result(kirim_telegram)
  File "nikeid-telegram-scrapper.py", line 104, in filtering_result
    for i in list_of_result: 
TypeError: 'NoneType' object is not iterable

**Comment by alionar** [comment]
hi @cynnek, can you give me nike store link when you tried that?

**Comment by cynnek** [comment]
hi @alionar, I was trying on this link: https://www.nike.com/sg/t/sb-dunk-high-pro-skate-shoe-kGrPh1/CV9499-100

Do you think it is possible to fetch all new items with this link https://www.nike.com/sg/w/new-mens-3n82yznik1?sort=newest?

**Comment by alionar** [comment]
i think you just provide `URL_SEARCH` config with this link https://www.nike.com/sg/w/new-mens-3n82yznik1?sort=newest

it will scrap all item in that page

**Comment by cynnek** [comment]
Thank you @alionar , the error is gone but it kept showing 0 results.

If I want to display every new items from that page, do I change the following?

  result = menu.find_all("div", class_="product-grid__items")
    if len(result) == 1:
        result_shoes = menu.find_all("div", class_="product-card css-1y22mjo css-z5nr6i css-11ziap1 css-zk7jxt css-dpr2cn product-grid__card")

**Comment by alionar** [comment]
sorry for late response @cynnek 

i think nike store keep change this tag for each products element, maybe i will fix it later and make it dynamic.

**Comment by alionar** [comment]
hi @cynnek , i already push the fix for this issue. Can you try it?

**Comment by cynnek** [comment]
hi @alionar, I appreciate the time taken looking into this :)

I have encountered issues with the function `filtering_result`:

  File "nikeid-telegram-scrapper.py", line 116, in filtering_result
    for i in list_of_result:
TypeError: 'NoneType' object is not iterable

**Comment by alionar** [comment]
Because i made this for scraping shoe items only, so you should comment [this row](https://github.com/alionar/nikeid-telegram-scrapper/blob/02e9d25787bd5d59a9ccffdcf8859bdccbcd38bf/nikeid-telegram-scrapper.py#L154) if you want to scrap another items beside shoes.

```
# Comment this (row 154)
# kirim_telegram = filtering_result(kirim_telegram)
```

<img width="698" alt="test" src="https://user-images.githubusercontent.com/18596757/84672420-bc53a980-af52-11ea-9743-7eb8a42b3b96.png">
